### ISSUE TITLE
AppBot + GitHub Issues

### ISSUE THREAD

**Issue by Joshuliu** [Joshuliu/AppBot#1]
Issues are used for getting help or reporting bugs. If you want to get faster help, you should join [the support server](https://bit.ly/appbot-help).

**Comment by TBNRShadowDev** [comment]
lol do you think we don't know how GitHub works?

**Comment by Joshuliu** [comment]
ur talking about urself only
"we" can be a noob

**Comment by TBNRShadowDev** [comment]
Fine, I correct it as a most people, because most people that have accounts on GitHub is here for opensource, so they know how stuff work
